
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

mqtt:
  broker: mosquitto

light:
  - platform: mqtt
    unique_id: 1
    name: "Lamp"
    command_topic: "light/1"
    qos: 1
    payload_on: "on"
    payload_off: "off"
    retain: true

lock:
  - platform: mqtt
    unique_id: 2
    name: "Door"
    command_topic: "door/1"
    qos: 1
    payload_unlock: "open"
    payload_lock: "close"
    state_unlocked: "OPEN"
    state_locked: "CLOSE"
    retain: true
    value_template: "Дверь"

switch:
  - platform: mqtt
    name: TV
    command_topic: "tv/1"
    payload_on: "on"
    payload_off: "off"
  - platform: mqtt
    name: Проектор  
    command_topic: "projector/1"
    payload_on: "on"
    payload_off: "off"

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
