version: "3.7"
services:
#  mosquitto:
#    image: eclipse-mosquitto
#    hostname: mosquitto
#    container_name: mosquitto
#    expose:
#      - "1883"
#      - "9001"
#    ports:
#      - "1883:1883"
#      - "9001:9001"
#    volumes:
#      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
#      - ./mosquitto/mosquitto.passwd:/mosquitto/config/mosquitto.passwd
#      - ./mosquitto/log/mosquitto.log:/mosquitto/log/mosquitto.log
#      - ./mosquitto/data:/mosquitto/data
#    networks:
#      - default

  mosquitto:
    build:
      context: mosquitto
      dockerfile: Dockerfile
      args:
        - MOSQUITTO_VERSION=${MOSQUITTO_VERSION:-latest}
    environment:
      - MOSQUITTO_USERNAME=mosquitto
      - MOSQUITTO_PASSWORD=mosquitto
    image: eclipse-mosquitto:${MOSQUITTO_VERSION:-latest}
    container_name: eclipse-mosquitto
    restart: always
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883

  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant
    volumes:
      # Local path where your home assistant config will be stored
      - ./homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    network_mode: host
    ports:
      - 8123:8123
    depends_on:
      - mariadb

  mariadb:
    image: mariadb/server:10.3
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: ha_db
      MYSQL_USER: homeassistant
      MYSQL_PASSWORD: changeme
    volumes:
      # Local path where the database will be stored.
      - ./mariadb:/var/lib/mysql

networks:
  iot:
    driver: bridge